apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
          - env: uat
          - env: prod
  template:
    metadata:
      name: '{{path.basename}}-{{env}}'
    spec:
      project: default
      source:
        repoURL: <REPO_URL>
        targetRevision: main
        path: apps/{{path.basename}}
        helm:
          valueFiles:
            - values/{{env}}.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}-{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
