apiVersion: v2
name: pifagor2-onboarding
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: main
    version: "0.0.7"
    repository: "git+https://github.com/PonamaryovMV/helm-base-charts.git"

